# Generated by Django 4.2.8 on 2024-01-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CitizenInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("image", models.ImageField(upload_to="images/")),
                ("address", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("input_date", models.DateField()),
            ],
        ),
    ]
