# Generated by Django 4.2.8 on 2024-01-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citizen", "0002_alter_citizeninput_input_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizeninput",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
