# Generated by Django 5.0.1 on 2024-02-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_alter_citizeninput_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizeninput',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
