# Generated by Django 5.0.1 on 2024-01-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='progress_images/')),
            ],
        ),
    ]
