# Generated by Django 5.0.1 on 2024-01-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleman', '0002_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='progress_images/')),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('input_date', models.DateField(null=True)),
            ],
        ),
    ]
